-- =============================================================================
-- SEED 112 — Municípios brasileiros com mais de 100 mil habitantes (Censo 2022)
-- Fonte: Wikipedia / IBGE — 319 municípios
-- IDEMPOTENTE (ON CONFLICT DO NOTHING)
-- =============================================================================

INSERT INTO cities (name, state_code) VALUES
  ('São Paulo', 'SP'),
  ('Rio de Janeiro', 'RJ'),
  ('Brasília', 'DF'),
  ('Fortaleza', 'CE'),
  ('Salvador', 'BA'),
  ('Belo Horizonte', 'MG'),
  ('Manaus', 'AM'),
  ('Curitiba', 'PR'),
  ('Recife', 'PE'),
  ('Goiânia', 'GO'),
  ('Porto Alegre', 'RS'),
  ('Belém', 'PA'),
  ('Guarulhos', 'SP'),
  ('Campinas', 'SP'),
  ('São Luís', 'MA'),
  ('Maceió', 'AL'),
  ('Campo Grande', 'MS'),
  ('São Gonçalo', 'RJ'),
  ('Teresina', 'PI'),
  ('João Pessoa', 'PB'),
  ('São Bernardo do Campo', 'SP'),
  ('Duque de Caxias', 'RJ'),
  ('Nova Iguaçu', 'RJ'),
  ('Natal', 'RN'),
  ('Santo André', 'SP'),
  ('Osasco', 'SP'),
  ('Sorocaba', 'SP'),
  ('Uberlândia', 'MG'),
  ('Ribeirão Preto', 'SP'),
  ('São José dos Campos', 'SP'),
  ('Cuiabá', 'MT'),
  ('Jaboatão dos Guararapes', 'PE'),
  ('Contagem', 'MG'),
  ('Joinville', 'SC'),
  ('Feira de Santana', 'BA'),
  ('Aracaju', 'SE'),
  ('Londrina', 'PR'),
  ('Juiz de Fora', 'MG'),
  ('Florianópolis', 'SC'),
  ('Aparecida de Goiânia', 'GO'),
  ('Serra', 'ES'),
  ('Campos dos Goytacazes', 'RJ'),
  ('Belford Roxo', 'RJ'),
  ('Niterói', 'RJ'),
  ('São José do Rio Preto', 'SP'),
  ('Ananindeua', 'PA'),
  ('Vila Velha', 'ES'),
  ('Caxias do Sul', 'RS'),
  ('Porto Velho', 'RO'),
  ('Mogi das Cruzes', 'SP'),
  ('Jundiaí', 'SP'),
  ('Macapá', 'AP'),
  ('São João de Meriti', 'RJ'),
  ('Piracicaba', 'SP'),
  ('Campina Grande', 'PB'),
  ('Santos', 'SP'),
  ('Mauá', 'SP'),
  ('Montes Claros', 'MG'),
  ('Boa Vista', 'RR'),
  ('Betim', 'MG'),
  ('Maringá', 'PR'),
  ('Anápolis', 'GO'),
  ('Diadema', 'SP'),
  ('Carapicuíba', 'SP'),
  ('Petrolina', 'PE'),
  ('Bauru', 'SP'),
  ('Caruaru', 'PE'),
  ('Vitória da Conquista', 'BA'),
  ('Itaquaquecetuba', 'SP'),
  ('Rio Branco', 'AC'),
  ('Blumenau', 'SC'),
  ('Ponta Grossa', 'PR'),
  ('Caucaia', 'CE'),
  ('Cariacica', 'ES'),
  ('Franca', 'SP'),
  ('Olinda', 'PE'),
  ('Praia Grande', 'SP'),
  ('Cascavel', 'PR'),
  ('Canoas', 'RS'),
  ('Paulista', 'PE'),
  ('Uberaba', 'MG'),
  ('Santarém', 'PA'),
  ('São Vicente', 'SP'),
  ('Ribeirão das Neves', 'MG'),
  ('São José dos Pinhais', 'PR'),
  ('Pelotas', 'RS'),
  ('Vitória', 'ES'),
  ('Barueri', 'SP'),
  ('Taubaté', 'SP'),
  ('Suzano', 'SP'),
  ('Palmas', 'TO'),
  ('Camaçari', 'BA'),
  ('Várzea Grande', 'MT'),
  ('Limeira', 'SP'),
  ('Guarujá', 'SP'),
  ('Juazeiro do Norte', 'CE'),
  ('Foz do Iguaçu', 'PR'),
  ('Sumaré', 'SP'),
  ('Petrópolis', 'RJ'),
  ('Cotia', 'SP'),
  ('Taboão da Serra', 'SP'),
  ('Imperatriz', 'MA'),
  ('Santa Maria', 'RS'),
  ('São José', 'SC'),
  ('Parauapebas', 'PA'),
  ('Marabá', 'PA'),
  ('Gravataí', 'RS'),
  ('Mossoró', 'RN'),
  ('Itajaí', 'SC'),
  ('Volta Redonda', 'RJ'),
  ('Governador Valadares', 'MG'),
  ('Indaiatuba', 'SP'),
  ('São Carlos', 'SP'),
  ('Chapecó', 'SC'),
  ('Parnamirim', 'RN'),
  ('Embu das Artes', 'SP'),
  ('Macaé', 'RJ'),
  ('Rondonópolis', 'MT'),
  ('São José de Ribamar', 'MA'),
  ('Dourados', 'MS'),
  ('Araraquara', 'SP'),
  ('Jacareí', 'SP'),
  ('Juazeiro', 'BA'),
  ('Marília', 'SP'),
  ('Americana', 'SP'),
  ('Hortolândia', 'SP'),
  ('Arapiraca', 'AL'),
  ('Maracanaú', 'CE'),
  ('Itapevi', 'SP'),
  ('Colombo', 'PR'),
  ('Divinópolis', 'MG'),
  ('Magé', 'RJ'),
  ('Ipatinga', 'MG'),
  ('Novo Hamburgo', 'RS'),
  ('Sete Lagoas', 'MG'),
  ('Rio Verde', 'GO'),
  ('Águas Lindas de Goiás', 'GO'),
  ('Presidente Prudente', 'SP'),
  ('Itaboraí', 'RJ'),
  ('Viamão', 'RS'),
  ('Palhoça', 'SC'),
  ('Cabo Frio', 'RJ'),
  ('Santa Luzia', 'MG'),
  ('São Leopoldo', 'RS'),
  ('Criciúma', 'SC'),
  ('Luziânia', 'GO'),
  ('Passo Fundo', 'RS'),
  ('Cabo de Santo Agostinho', 'PE'),
  ('Lauro de Freitas', 'BA'),
  ('Sobral', 'CE'),
  ('Rio Claro', 'SP'),
  ('Araçatuba', 'SP'),
  ('Valparaíso de Goiás', 'GO'),
  ('Maricá', 'RJ'),
  ('Sinop', 'MT'),
  ('Nossa Senhora do Socorro', 'SE'),
  ('Castanhal', 'PA'),
  ('Rio Grande', 'RS'),
  ('Nova Friburgo', 'RJ'),
  ('Alvorada', 'RS'),
  ('Itabuna', 'BA'),
  ('Cachoeiro de Itapemirim', 'ES'),
  ('Santa Bárbara d''Oeste', 'SP'),
  ('Jaraguá do Sul', 'SC'),
  ('Guarapuava', 'PR'),
  ('Ferraz de Vasconcelos', 'SP'),
  ('Ilhéus', 'BA'),
  ('Bragança Paulista', 'SP'),
  ('Timon', 'MA'),
  ('Araguaína', 'TO'),
  ('Ibirité', 'MG'),
  ('Barra Mansa', 'RJ'),
  ('Porto Seguro', 'BA'),
  ('Itu', 'SP'),
  ('Angra dos Reis', 'RJ'),
  ('Mesquita', 'RJ'),
  ('Linhares', 'ES'),
  ('São Caetano do Sul', 'SP'),
  ('Pindamonhangaba', 'SP'),
  ('Francisco Morato', 'SP'),
  ('Teresópolis', 'RJ'),
  ('Lages', 'SC'),
  ('Poços de Caldas', 'MG'),
  ('Parnaíba', 'PI'),
  ('Barreiras', 'BA'),
  ('Patos de Minas', 'MG'),
  ('Jequié', 'BA'),
  ('Atibaia', 'SP'),
  ('Itapecerica da Serra', 'SP'),
  ('Abaetetuba', 'PA'),
  ('Itapetininga', 'SP'),
  ('Caxias', 'MA'),
  ('Rio das Ostras', 'RJ'),
  ('Senador Canedo', 'GO'),
  ('Santana de Parnaíba', 'SP'),
  ('Mogi Guaçu', 'SP'),
  ('Pouso Alegre', 'MG'),
  ('Araucária', 'PR'),
  ('Alagoinhas', 'BA'),
  ('Toledo', 'PR'),
  ('Santa Rita', 'PB'),
  ('Fazenda Rio Grande', 'PR'),
  ('Camaragibe', 'PE'),
  ('Nilópolis', 'RJ'),
  ('Paranaguá', 'PR'),
  ('Paço do Lumiar', 'MA'),
  ('Teixeira de Freitas', 'BA'),
  ('Botucatu', 'SP'),
  ('Franco da Rocha', 'SP'),
  ('Garanhuns', 'PE'),
  ('Trindade', 'GO'),
  ('Brusque', 'SC'),
  ('Queimados', 'RJ'),
  ('Balneário Camboriú', 'SC'),
  ('Teófilo Otoni', 'MG'),
  ('Varginha', 'MG'),
  ('Campo Largo', 'PR'),
  ('Cachoeirinha', 'RS'),
  ('Caraguatatuba', 'SP'),
  ('Salto', 'SP'),
  ('Cametá', 'PA'),
  ('Vitória de Santo Antão', 'PE'),
  ('Jaú', 'SP'),
  ('Santa Cruz do Sul', 'RS'),
  ('Três Lagoas', 'MS'),
  ('Sapucaia do Sul', 'RS'),
  ('Conselheiro Lafaiete', 'MG'),
  ('Itapipoca', 'CE'),
  ('Crato', 'CE'),
  ('Araras', 'SP'),
  ('Apucarana', 'PR'),
  ('Araruama', 'RJ'),
  ('Resende', 'RJ'),
  ('Sabará', 'MG'),
  ('Vespasiano', 'MG'),
  ('Votorantim', 'SP'),
  ('Pinhais', 'PR'),
  ('Sertãozinho', 'SP'),
  ('Barcarena', 'PA'),
  ('Valinhos', 'SP'),
  ('Altamira', 'PA'),
  ('Barbacena', 'MG'),
  ('Guarapari', 'ES'),
  ('Ji-Paraná', 'RO'),
  ('Tatuí', 'SP'),
  ('São Mateus', 'ES'),
  ('Itaituba', 'PA'),
  ('Bento Gonçalves', 'RS'),
  ('Bragança', 'PA'),
  ('Barretos', 'SP'),
  ('Itatiba', 'SP'),
  ('Colatina', 'ES'),
  ('Almirante Tamandaré', 'PR'),
  ('Arapongas', 'PR'),
  ('Birigui', 'SP'),
  ('Piraquara', 'PR'),
  ('Sarandi', 'PR'),
  ('Jandira', 'SP'),
  ('Guaratinguetá', 'SP'),
  ('Bagé', 'RS'),
  ('Araguari', 'MG'),
  ('Uruguaiana', 'RS'),
  ('Umuarama', 'PR'),
  ('Itaguaí', 'RJ'),
  ('Formosa', 'GO'),
  ('São Gonçalo do Amarante', 'RN'),
  ('Catanduva', 'SP'),
  ('Várzea Paulista', 'SP'),
  ('Ribeirão Pires', 'SP'),
  ('Igarassu', 'PE'),
  ('Simões Filho', 'BA'),
  ('Catalão', 'GO'),
  ('Codó', 'MA'),
  ('Eunápolis', 'BA'),
  ('Itabira', 'MG'),
  ('Paulo Afonso', 'BA'),
  ('Itanhaém', 'SP'),
  ('Cubatão', 'SP'),
  ('Passos', 'MG'),
  ('Marituba', 'PA'),
  ('Nova Lima', 'MG'),
  ('Araxá', 'MG'),
  ('São Lourenço da Mata', 'PE'),
  ('Sorriso', 'MT'),
  ('Paulínia', 'SP'),
  ('Tubarão', 'SC'),
  ('Itumbiara', 'GO'),
  ('Luís Eduardo Magalhães', 'BA'),
  ('Santana', 'AP'),
  ('Cambé', 'PR'),
  ('Breves', 'PA'),
  ('Açailândia', 'MA'),
  ('Tangará da Serra', 'MT'),
  ('Jataí', 'GO'),
  ('Erechim', 'RS'),
  ('Nova Serrana', 'MG'),
  ('Paragominas', 'PA'),
  ('Maranguape', 'CE'),
  ('Planaltina', 'GO'),
  ('Lavras', 'MG'),
  ('Coronel Fabriciano', 'MG'),
  ('Muriaé', 'MG'),
  ('São Pedro da Aldeia', 'RJ'),
  ('Ourinhos', 'SP'),
  ('Novo Gama', 'GO'),
  ('Poá', 'SP'),
  ('Bacabal', 'MA'),
  ('Itacoatiara', 'AM'),
  ('Itabaiana', 'SE'),
  ('Ubá', 'MG'),
  ('Patos', 'PB'),
  ('Camboriú', 'SC'),
  ('Santo Antônio de Jesus', 'BA'),
  ('Ituiutaba', 'MG'),
  ('Manacapuru', 'AM'),
  ('Balsas', 'MA'),
  ('Lagarto', 'SE'),
  ('Assis', 'SP'),
  ('Itaperuna', 'RJ')
ON CONFLICT (country_code, state_code, name) DO NOTHING;
